AllCops:
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

AccessorMethodName:
  Enabled: false

TrivialAccessors:
  Enabled: false

ModuleLength:
  Enabled: false

LineLength:
  Max: 150

MethodLength:
  Max: 20

Style/RegexpLiteral:
  Enabled: false
