# Mac - High Sierra - browser stack config

common_caps:
  "project": "Player Browserstack"
  "build": "High Sierra - Mac"
  "browserstack.debug": true
  "browserstack.geolocation": "DE"
  "browserstack.networkLogs": "false"

browser_caps:
  -
    "os": "OS X"
    "os_version": "El Capitan"
    "browser": "Chrome"
    "name": "Chrome"
    "browserstack.console": "errors"
  -
    "os": "OS X"
    "os_version": "El Capitan"
    "browser": "Firefox"
    "name": "Firefox"
    "browserstack.console": "errors"
  -
    "os": "OS X"
    "os_version": "El Capitan"
    "browser": "Safari" 
    "name": "Safari"
  -
    "os": "OS X"
    "os_version": "El Capitan"
    "browser": "Opera" 
    "name": "Opera"
    