# Single use Browserstack config file - combinations can be found https://www.browserstack.com/list-of-browsers-and-platforms?product=automate
common_caps:
  "project": "Player Browserstack"
  "build": "<OS_VERSION>"
  "browserstack.debug": true
  "browserstack.geoLocation": "DE"
  "browserstack.networkLogs": "false"

browser_caps:
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "Firefox"
    "name": "<SESSION_NAME>"
    "browserstack.console": "errors"
