# Windows - 8.1 - browser stack config

common_caps:
  "project": "Player Browserstack"
  "build": "Windows 8.1"
  "browserstack.debug": true
  "browserstack.geolocation": "DE"
  "browserstack.networkLogs": "false"

browser_caps:
  -
    "os": "Windows"
    "os_version": "8.1"
    "browser": "Chrome"
    "name": "Chrome"
    "browserstack.console": "errors"
  -
    "os": "Windows"
    "os_version": "8.1"
    "browser": "Firefox"
    "name": "Firefox"
    "browserstack.console": "errors"
  -
    "os": "Windows"
    "os_version": "8.1"
    "browser": "Opera" 
    "name": "Opera"
  -
    "os": "Windows"
    "os_version": "8.1"
    "browser": "IE"
    "name": "IE 11"
